# Generated by Django 3.2.11 on 2022-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=5)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
